title: Florent P.

logo: fp.png

description: Data science and AI

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: florent.proust@wanadoo.fr
